version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users-api
      MYSQL_PASSWORD: root
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached-container
    ports:
      - "11211:11211"
    networks:
      - app-network

  mongo:
    image: mongo:5
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-container
    ports:
      - "5672:5672"
      - "15672:15672" # Interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    networks:
      - app-network
  
  solr:
    image: solr:latest
    container_name: solr-container
    ports:
      - "8983:8983"
    volumes:
      - ./search-api/solr-config:/opt/solr/server/solr/courses
    command: solr-create -c courses
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8085:8085"
    volumes:
      - ./search-api/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - search-api1
      - search-api2
    networks:
      - app-network

  courses-api:
    image: courses-api:latest
    container_name: courses-api-container
    build:
      context: ./courses-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: /bin/sh -c "sleep 30 && go run main.go"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network
  
  search-api1:
    image: search-api:latest
    container_name: search-api1-container
    build:
      context: ./search-api
      dockerfile: Dockerfile
    # Puedes omitir el mapeo de puertos si solo se usará internamente.
    # Si necesitas exponerlo al host, mapea el puerto del contenedor a uno disponible:
    ports:
      - "8082:8082"
    command: /bin/sh -c "sleep 30 && go run main.go"
    depends_on:
      - rabbitmq
      - solr
    networks:
      - app-network

  search-api2:
    image: search-api:latest
    container_name: search-api2-container
    build:
      context: ./search-api
      dockerfile: Dockerfile
    # Si necesitas exponerlo, usa otro puerto en el host:
    ports:
      - "8083:8082"  # Aquí el contenedor sigue escuchando en el 8082, pero se mapea al 8083 en el host.
    command: /bin/sh -c "sleep 30 && go run main.go"
    depends_on:
      - rabbitmq
      - solr
    networks:
      - app-network

  users-api:
    image: users-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: users-api-container
    build:
      context: ./users-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: /bin/sh -c "sleep 10 && go run main.go"
    depends_on:
      - memcached
      - mysql
    networks:
      - app-network
  
  # inscriptions-api:
  #   image: inscriptions-api:latest
  #   container_name: inscriptions-api-container
  #   build:
  #     context: ./inscriptions-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   command: /bin/sh -c "sleep 30 && go run main.go"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network

  frontend:
    image: frontend-api:latest
    container_name: frontend-container
    build: ./frontend
    depends_on:
      - courses-api
      - search-api1
      - search-api2 
      # - inscriptions-api
    ports:
      - "5173:5173"

      
networks:
  app-network:
    driver: bridge